### ISSUE TITLE
run example locally without docker

### ISSUE THREAD

**Issue by huiwang** [kbastani/spring-cloud-microservice-example#31]
Hello All, 

I have one question regarding the bootstrap file, for example [the one](https://github.com/kbastani/spring-cloud-microservice-example/blob/master/movie-microservice/src/main/resources/bootstrap.yml) in movie-microservice.

In that file, we point to the config server with "uri: http://configserver:8888". However, the hostname configserver makes sense only services are started with docker-compose if I understood it well. 

Therefore, when I start the service locally in my ide for example without docker, I can't resolve the domain name.

I think the profile feature can help us to resolve this problem but all profile related resources I found is about the configserver but not on the bootstrap file. 

Can someone help me out please ?

Thanks,
Hui

**Comment by huiwang** [comment]
I think i get the answer 

```
spring:
  application:
    name: movie
  cloud:
    config:
      uri: http://configserver:8888
encrypt:
  failOnError: false
```
goes to 

```
spring:
  application:
    name: movie
  cloud:
    config:
      uri: http://configserver:8888
encrypt:
  failOnError: false

---
spring:
  profiles: development
  cloud:
    config:
      uri: http://localhost:8888
```

Then start the service with `-Dspring.profiles.active=development`.
